### ISSUE TITLE
StackOverflowError when running FoldableTests

### ISSUE THREAD

**Issue by ceedubs** [milessabin/kittens#1]
From current master (4982a3b):

> [info] FoldableTests:
[info] Exception encountered when attempting to run a suite with class name: cats.derived.FoldableTests *** ABORTED ***
[info]   java.lang.StackOverflowError:
[info]   at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
[info]   at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)

**Comment by milessabin** [comment]
I think this is actually most likely an issue with `Fold` in Cats itself ... should be fixed by https://github.com/non/cats/pull/391. Paging @non ...

**Comment by milessabin** [comment]
Did you change anything in the tests to provoke that SOE? If not, then I think this is fixed, thanks to the upstream Cats changes I pointed at.

**Comment by ceedubs** [comment]
I didn't change anything, so I suspect you are right. Closing.

**Comment by milessabin** [comment]
Thanks :-)
