### ISSUE TITLE
2.12 build

### ISSUE THREAD

**Issue by adamw** [milessabin/kittens#30]
Would be great to have a 2.12 build. However it seems it's not as easy as extending the cross versions setting :)

**Comment by kailuowang** [comment]
I am working on this one.

**Comment by kailuowang** [comment]
@adamw do you need a 2.12 build against cats 0.8.1 ? or is it okay we have a 2.12 build against cats 0.9.0 (just released). Either case I plan to try get the release out Tuesday.

**Comment by adamw** [comment]
A build against 0.9.0 would be just fine for me :) Thanks!
