### ISSUE TITLE
cats.derived.show

### ISSUE THREAD

**Issue by fommil** [milessabin/kittens#40]
it would be useful to have typeclass derivation for `cats.Show` for (labelled) products and coproducts. I guess even unlabelled products/coproducts could be useful too but I have no usecase for that.

**Comment by kailuowang** [comment]
I suppose that this generated instance should try to use the `show` instances of the fields as well. Should the derivation fail if there are fields missing show instances, or should it delegate to `toString`?

**Comment by fommil** [comment]
avoid `toString` and just work for things with `LabelledGeneric` and (arguably) `Generic`.

It could perhaps include `""` around strings in case classes :smile:

I should imagine this is pretty simple, almost textbook, application of shapeless typeclass derivation.

**Comment by kailuowang** [comment]
fixed by #48
