### ISSUE TITLE
Minimal imports for automatic case-class Monoids

### ISSUE THREAD

**Issue by ryan-williams** [milessabin/kittens#49]
I was pointed at this library [in gitter](https://gitter.im/milessabin/shapeless?at=5994a48a162adb6d2e01a076), thanks @joroKr21!

AFAICT, the easiest way to get automatic `cats.Monoid`s for case-classes is:

```scala
import cats.derived.monoid._, legacy._
```

Is that right? I couldn't tell if the "`legacy`" bit implies there's a better way, / I was hoping for just one import 😆 

IntelliJ's "Optimize Imports" wants to split these onto two lines:

```scala
import cats.derived.monoid._
import cats.derived.monoid.legacy._
```

and then it marks the first one as unused, so a subsequent "Optimize Imports" will break compilation! 

I might file a bug against the IJ scala plugin about that, but if there's another way here I'd like to know as well.

Thanks!

**Comment by milessabin** [comment]
The name `legacy` is itself a legacy ... at one point I thought it might make sense for Cats to have a first class dependency on export-hook and use its mechanisms for prioritizing type class instances. `legacy` was meant to convey the idea of a mechanism that supported Cats prior to the arrival of export-hook.

Cats never got that export-hook dependency though, and I no longer think it would be a good idea if it did, so `legacy` is now a bit of a misnomer.

I'm going to close this ticket now. If you have questions about Kittens the best place to ask is its [gitter channel](https://gitter.im/milessabin/kittens). Intellij bugs should be reported on their own issue tracker.
