### ISSUE TITLE
Monad, Monoid, MonoidK issues

### ISSUE THREAD

**Issue by DmytroMitin** [milessabin/kittens#51]
The following code works fine:
```
import cats.kernel.Monoid
import cats.{Foldable, Functor, Monad, MonoidK}
import cats.derived._

object App {
  sealed trait MyTrait[A]
  case class MyClass1[A](a: A, a1: A, a2: A) extends MyTrait[A]
  case class MyClass2[A](a: A, a1: A) extends MyTrait[A]

  def main(args: Array[String]): Unit = {

    import functor._, functor.legacy._
    println(Functor[MyClass1].map(MyClass1(1, 2, 3))(_ + 1))
    println(Functor[MyTrait].map(MyClass1(1, 2, 3).asInstanceOf[MyTrait[Int]])(_ + 1))
    import cats.syntax.functor._
    println(MyClass1(1, 2, 3).map(_ + 1)) //MyClass1(2,3,4)

    import foldable._, foldable.legacy._
    println(Foldable[MyClass1].foldLeft(MyClass1(1, 2, 3), 0)(_ + _))
    import cats.syntax.foldable._
    println(MyClass1(1, 2, 3).foldLeft(0)(_ + _))
    println(MyClass1(1, 2, 3).asInstanceOf[MyTrait[Int]].foldLeft(0)(_ + _)) // 6
  }
}
```
But if I try either of the following I have errors:
```
    import monad._, monad.legacy._
    println(Monad[MyClass1].>>=(MyClass1(1, 2, 3))(x => MyClass1(x + 1, x * 2, x * x)))

    import monoid._, monoid.legacy._
    println(Monoid[MyClass1[Int]].combine(MyClass1(1, 2, 3), MyClass1(4, 5, 6)))

    import monoidk._, monoidk.legacy._
    println(MonoidK[MyClass1].algebra[Int].combine(MyClass1(1, 2, 3), MyClass1(4, 5, 6)))
```
My build.sbt is
```
name := "demo"
version := "0.1"
scalaOrganization := "org.typelevel"
scalaVersion := "2.12.3-bin-typelevel-4"
libraryDependencies += "org.typelevel" %% "kittens" % "1.0.0-M11"
scalacOptions += "-Ypartial-unification"
scalacOptions += "-Xlog-implicits"
```
Error messages:
Monad https://gist.github.com/DmytroMitin/56e495ef5da17d36e103f9253e584d81
Monoid https://gist.github.com/DmytroMitin/9d3bca41a5e567f3c32e715ca928f2a1
MonoidK https://gist.github.com/DmytroMitin/f92cafda428f4608019618a230e76461

**Comment by milessabin** [comment]
You're missing the import for the atomic instances (eg. for `Int`). Try adding,
```scala
import cats.implicits._
```

**Comment by DmytroMitin** [comment]
@milessabin 
Thank you. With this additional import the code
```
import cats.Monad
import cats.instances.int._

object App {
  sealed trait MyTrait[A]
  case class MyClass1[A](a: A, a1: A, a2: A) extends MyTrait[A]
  case class MyClass2[A](a: A, a1: A) extends MyTrait[A]

  def main(args: Array[String]): Unit = {
    import cats.derived._, monad._, monad.legacy._
    println(Monad[MyClass1].>>=(MyClass1(1, 2, 3))(x => MyClass1(x + 1, x * 2, x * x)))
  }
}
```
produces errors https://gist.github.com/DmytroMitin/435bad2654dc3da5995aa46a73636443

**Comment by DmytroMitin** [comment]
@milessabin 
Maybe the thing is not in `import cats.instances.int._` since it brings Show[Int], Order[Int], CommutativeGroup[Int] only and they seem to be not needed for Monad. If I import `cats.instances.list._` without `cats.instances.int._` then standard Monad (without derivation) works:
`println(Monad[List].>>=(List(1, 2, 3))(x => List(x + 1, x * 2, x * x))) //List(2, 2, 1, 3, 4, 4, 4, 6, 9)`

**Comment by joroKr21** [comment]
How do you expect to derive a `Monad[MyClass1]`? How would you implement `>>=`?

**Comment by DmytroMitin** [comment]
@joroKr21 
```
Monad[MyClass1].>>=(MyClass1(1, 2, 3))(x => MyClass1(x + 1, x * 2, x * x))
MyClass1(2, 4, 9)
Monad[MyClass1].pure(1)
MyClass1(1, 1, 1)
```
Such instance satisfies monad laws. For coproducts it's trickier.

Anyway suppose I wouldn't expect to have derived instances for Applicative and Monad (on contrary to Functor, Foldable and Traversable) as [in Haskell](https://downloads.haskell.org/~ghc/latest/docs/html/users_guide/glasgow_exts.html#extensions-to-the-deriving-mechanism).
What does `cats/derived/monad.scala` do in kittens then?

**Comment by kailuowang** [comment]
It's an experiment derivation of `Monad` instances. Right now it's too slow compilation time to be of practical use. I am proposing removing them.

**Comment by DmytroMitin** [comment]
@kailuowang 
Even if it's slow how does it work?
What is `Monad[MyClass1].>>=(MyClass1(1, 2, 3))(x => MyClass1(x + 1, x * 2, x * x))`? (Did I guess correctly that it's `MyClass1(2, 4, 9)`?)
And what is `Monad[MyTrait].>>=(MyClass1(1, 2, 3))(x => MyClass2(x + 1, x * 2, x * x))`?

**Comment by kailuowang** [comment]
@DmytroMitin It doesn't generate for such classes. Please see the tests and code to see what it does. But again, my preference is to remove it all together.

**Comment by kailuowang** [comment]
do you mind retry this with the latest RC0 release? note that `Monad` is removed.

**Comment by DmytroMitin** [comment]
@kailuowang 
Thank you. Now Monoid works
```
import cats.kernel.Monoid
import cats.{Foldable, Functor, MonoidK}
import cats.derived._

object App {

  sealed trait MyTrait[A]
  case class MyClass1[A](a: A, a1: A, a2: A) extends MyTrait[A]
  case class MyClass2[A](a: A, a1: A) extends MyTrait[A]

  def main(args: Array[String]): Unit = {

    import functor._
    println(Functor[MyClass1].map(MyClass1(1, 2, 3))(_ + 1)) // MyClass1(2,3,4)
    println(Functor[MyTrait].map(MyClass1(1, 2, 3).asInstanceOf[MyTrait[Int]])(_ + 1)) // MyClass1(2,3,4)
    import cats.syntax.functor._
    println(MyClass1(1, 2, 3).map(_ + 1)) // MyClass1(2,3,4)

    import foldable._
    println(Foldable[MyClass1].foldLeft(MyClass1(1, 2, 3), 0)(_ + _)) // 6
    import cats.syntax.foldable._
    println(MyClass1(1, 2, 3).foldLeft(0)(_ + _)) // 6
    println(MyClass1(1, 2, 3).asInstanceOf[MyTrait[Int]].foldLeft(0)(_ + _)) // 6

    import monoid._
    println(Monoid[MyClass1[Int]].combine(MyClass1(1, 2, 3), MyClass1(4, 5, 6))) // MyClass1(5,7,9)
    import cats.syntax.monoid._
    println(MyClass1(1, 2, 3) combine MyClass1(4, 5, 6)) // MyClass1(5,7,9)
  }
}
```
but MonoidK doesn't
```
    import monoidK._
    println(MonoidK[MyClass1].algebra[Int].combine(MyClass1(1, 2, 3), MyClass1(4, 5, 6)))
```
```
Error:(46, 20) could not find implicit value for parameter instance: cats.MonoidK[course4.App13_kitten.MyClass1]
    println(MonoidK[MyClass1].algebra[Int].combine(MyClass1(1, 2, 3), MyClass1(4, 5, 6)))
```

**Comment by kailuowang** [comment]
Not sure a `MonoidK` for things like `case class MyClass2[A](a: A, a1: A)` can be derived. 
How would you manually write a `MonoidK` instance for it?

**Comment by DmytroMitin** [comment]
@kailuowang You're right. We can define `MonoidK`'s `empty[A]` and `combineK[A]` only for `A : Monoid`, not for every `A`.

**Comment by DmytroMitin** [comment]
@kailuowang Ok, but what does `cats/derived/monoidK.scala` do in kettens then?

**Comment by kailuowang** [comment]
Works for a `case class A[T](ot : Option [T])`
