### ISSUE TITLE
Remove ConsK

### ISSUE THREAD

**Issue by joroKr21** [milessabin/kittens#58]
`ConsK` is not part of cats or alleycats and it was used only for the derivation of `Apply`, `Applicative` and `Monad` which are removed since 2b1cf75. I guess that makes `ConsK` kind of dead code so we can remove it too.

**Comment by kailuowang** [comment]
It's from alleycats...

**Comment by joroKr21** [comment]
My bad :innocent:

**Comment by kailuowang** [comment]
No worries. Thanks for contributing!
