### ISSUE TITLE
Remove unnecessary uses of Lazy

### ISSUE THREAD

**Issue by joroKr21** [milessabin/kittens#61]
For recursive types it seems that only `Lazy[gen.Repr]` is necessary. `Lazy[H]` and `Lazy[T]` for `H :: T` as well as `Lazy[L]` and `Lazy[R]` for `L :+: R` are redundant and we can remove them. Or at least we should remove `Lazy[T]` and `Lazy[R]` since there is no chance to see the same type in this position. The problem with `Lazy` is that it increases compile time and memory footprint. Even worse thanks to milessabin/shapeless#776 which makes it difficult to diagnose OOM errors caused by implicit resolution for large ADTs.

**Comment by kailuowang** [comment]
I suspected we can remove those. I can take a stab on them unless someone beat me to it ;)

**Comment by joroKr21** [comment]
I'm still not sure what is the best structure. What do you think about `Lazy[Head]` and `Strict[Repr]`? This should avoid diverging implicit errors and at the same time keep laziness to a minimum.

**Comment by kailuowang** [comment]
` Lazy[Head]`, vanilla `Tail` and `Strict[Repr]` sounds worth a try.

**Comment by milessabin** [comment]
I don't recommend using `Strict` ...

In the short term if you can drop `Lazy` without breaking things then do that.

Longer term `Lazy` will all go away in favour of by-name implicits, `Cached` will go away in favour of general transparent instance caching and `Strict` will go away without a replacement.
