### ISSUE TITLE
Save code duplication by using implicit OrElse combinator

### ISSUE THREAD

**Issue by joroKr21** [milessabin/kittens#72]
#63 introduced changes that make it convenient for the user to derive type classes for nested ADTs without introducing ambiguities, but the cost was some code duplication in Kittens. It just occurred to me that we can eliminate the boilerplate again by using an `A OrElse B` combinator which is essentially a copy of `Either` but tries to resolve implicitly first `A` and then `B`. Does that make sense?

**Comment by kailuowang** [comment]
That sounds promising, do you wanna give it a try?

**Comment by joroKr21** [comment]
I will :+1: My only concern is that a change like this would touch every file. Will try to break it down.

**Comment by kailuowang** [comment]
You can try with one file to see if it works. I can change the rest if you don't have time

**Comment by joroKr21** [comment]
Superseded by #82
