### ISSUE TITLE
Full-auto derivation

### ISSUE THREAD

**Issue by durban** [milessabin/kittens#77]
Previously I've used `import cats.derived.eq._` to get fully automatic derivation. This is now deprecated, and the message says to "use cats.derive.eq instead". However, as far as I can tell, that doesn't really replaces the now deprecated solution (it's semi-automatic as described in #63).

Using `import cats.derived.MkEq._` seems to work. Is that now the recommended import?

**Comment by kailuowang** [comment]
The main thing is that we removed the `ExportHook` which was the mechanism of managing priority of instances.  So `import cats.derived.MkEq._` works but it would probably clash with existing `Eq` instances in the scope. While if you use `implicit val e: Eq[T] = cats.derive.eq[T]` it would avoid clashing and respect the existing instances. 
So a little bit more typing unfortunately but safer.

**Comment by kailuowang** [comment]
We can apply the same design used in https://github.com/milessabin/kittens/pull/73 by @joroKr21 to all TC derivations to restore full-auto derivaton

**Comment by durban** [comment]
Sounds good. (I'm using full-auto derivation, and I'd like to continue using it :-)

**Comment by kailuowang** [comment]
fixed by #85
