### ISSUE TITLE
Restore full auto derivation

### ISSUE THREAD

**Issue by joroKr21** [milessabin/kittens#82]
Let's divide and conquer.
Similar to #73 
If you have time, pick one and comment here:

- [x] `Empty`
- [ ] `EmptyK`
- [ ] `Eq`
- [ ] `Foldable`
- [x] `Functor`
- [ ] `Monoid`
- [ ] `MonoidK`
- [ ] `Pure`
- [ ] `Semigroup`
- [ ] `SemigroupK`
- [x] `Show`

**Comment by kailuowang** [comment]
Thanks @joroKr21 
I will work on `Show` today.

**Comment by joroKr21** [comment]
Sorry, I didn't have much time for this. Working on `EmptyK` now.
Duplicating the tests is a bit annoying but I don't see anything we can do here.

**Comment by kailuowang** [comment]
I may find some time to work on `Eq` today

**Comment by kailuowang** [comment]
fixed by #85
