### ISSUE TITLE
Deriving Order

### ISSUE THREAD

**Issue by torgeirsh** [milessabin/kittens#87]
There seems to be no support for deriving Order. Is it just an oversight, or is a technical issue preventing it? shapeless-contrib used to have support for scalaz Order.

**Comment by milessabin** [comment]
Not so much an oversight as Just Missing ... do you want to take a swing at it?

**Comment by torgeirsh** [comment]
I had a brief try at duplicating the code for Eq, but I just get "could not find implicit value" errors, and unfortunately can't spend time debugging and getting familiar with the internals right now.

**Comment by kailuowang** [comment]
@torgeirsh if you kindly submit a PR with your WIP, I will try take a stab when I get some free time.

**Comment by torgeirsh** [comment]
@kailuowang Sorry, but I didn't keep the code, as it was a very quick hack outside the project tree. Basically I just copied the code for deriving Eq to a new file, replaced everything with Order, and sprinkled NotImplementedExceptions in the compare implementations.

**Comment by kailuowang** [comment]
For products with multiple fields how do we order? prioritize from left to right? 
How do we order coproduct? maybe only provide PartialOrder for coproduct?

**Comment by milessabin** [comment]
I'd say yes to both.

**Comment by torgeirsh** [comment]
For what it's worth, shapeless-contrib provided scalaz.Order for coproduct as well, with the following implementation:
```
   def order(x: λ, y: λ) = (x, y) match {
	    case (Inl(a), Inl(b)) => L.order(a, b)
	    case (Inl(_), Inr(_)) => Ordering.LT
	    case (Inr(_), Inl(_)) => Ordering.GT
	    case (Inr(a), Inr(b)) => R.order(a, b)
	  }
```
I don't know what the pros and cons are, compared to PartialOrder.

**Comment by kailuowang** [comment]
I don't know how I feel about that. It seems even more arbitrary than the left to right order in product. For product, another question poped up: shall we skip on fields without order instance or simply fail the derivation there. 
Now I think about it, I think it's rather arbitrary for classes with more than one field, and auto-derivation is not that necessary for classes with one field. 
I am curious what's your actual use case @torgeirsh?

**Comment by milessabin** [comment]
I would fail if any fields don't have instances.

**Comment by kailuowang** [comment]
"when any ordering" will do how about just use the hashCode? 
```scala
implicit def arbOrder[A](implicit r: Refute[Order[A]]): Order[A] = Order.by((_:A).hashCode)
```
The `shapeless.Refute` is here so that it doesn't conflict with types with existing Order instance in scope.

**Comment by torgeirsh** [comment]
That's a clever idea! Unfortunately, I believe two different values can get the same hash code if you're unlucky?

**Comment by kailuowang** [comment]
sorry I was only suggesting it for test code. You can probably mix more things with hashCode to make it more consistent with the universal equality. 
but now I do see a non-test-only use case for an arbitrary Order that is consistent with Eq.

**Comment by benhutchison** [comment]
"I do see a non-test-only use case for an arbitrary Order that is consistent with Eq" <= +1 to that

**Comment by kailuowang** [comment]
Thanks to @Qi77Qi we have `PartialOrder` now. I think we just need an `Order` for `Product` to release 1.0.0

**Comment by kailuowang** [comment]
fixed by #91

**Comment by torgeirsh** [comment]
Great! I only see a Coproduct instance for PartialOrder though, does that mean it's not possible to derive Order for ADTs, or is there some magic behind the scenes?

**Comment by kailuowang** [comment]
We just felt that an derived `Order` for a coproduct would be too arbitrary to compare different types. It's not really a deal breaker to me though. What do you think @milessabin

**Comment by ykycxzsv** [comment]
If it's possible to provide the coproduct instances in local scope and reuse the product instances from the library, it's not too much of a pain point, but I really think an arbitrary ordering is useful for things like ordered trees. If a less arbitrary ordering is required for a type, it can be provided manually.

**Comment by torgeirsh** [comment]
If it's possible to provide the coproduct instances in local scope and reuse the product instances from the library, it's not too much of a pain point, but I really think an arbitrary ordering is useful for things like ordered trees. If a less arbitrary ordering is required for a type, it can be provided manually.

**Comment by milessabin** [comment]
I think it would make sense to provide a coproduct ordering as well.

**Comment by kailuowang** [comment]
okay I'm reopening it.

**Comment by torgeirsh** [comment]
This works for me in 1.0.0, thanks a lot!
