### ISSUE TITLE
[Meta] Make kitten an official outside module of Cats? 

### ISSUE THREAD

**Issue by kailuowang** [milessabin/kittens#96]
1.0 has been released for a while, I wonder if it would be a good idea to list it as a Cats module in a separate repo like `cats-effect` and `cats-mtl`.
 The instance derivation could be very handy for Cats users. And having it there will help adoption. 
What do you guys think?

**Comment by milessabin** [comment]
That gets a big 👍from me 🙂

**Comment by kailuowang** [comment]
Great. In that case, do you want to leave it as is or move GitHub repo to typelevel org?

**Comment by milessabin** [comment]
What are the benefits of moving the repo? Any downsides?

**Comment by kailuowang** [comment]
Not much difference either way to me. I asked merely because right now all other separate repo cats modules are under typelevel. `cats-effect` started under typelevel, owners of `mouse` and `cats-mtl` move them to under typelevel when they formally became Cats modules. 

Downsides: 
* Urls (github and git repo) change may cause confusion.
* Github repo ownership transferred to typelevel (but you are admin of the typelevel org too, so maybe not an issue)

Benefits:
* consistency with other outside cats-modules. 
* adds to the formality of being an official Cats module.
* it's already published under `org.typelevel` , so having repo under typelevel adds to consistency. 

I'd say just like with mouse and cats-mtl, it's your repo and your call.

**Comment by milessabin** [comment]
OK, the main negative is the url change. I think Kittens is probably not widely known enough for that to matter all that much. Being under the typelevel organization is likely to give it more exposure than it has currently, which I think offsets that problem somewhat.

OK, I'll transfer and announce the move.
